apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sat-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: AUTH_COOKIE_SECURE
              value: "false"
            - name: AUTH_COOKIE_SAME_SITE
              value: Lax
