apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: git-sat-backend-config
    literals:
      - SPRING_PROFILES_ACTIVE=default
      - NVIDIA_API_BASE=https://integrate.api.nvidia.com/v1
      - NVIDIA_MODEL=openai/gpt-oss-20b
      - AUTH_COOKIE_SECURE=true
      - AUTH_COOKIE_SAME_SITE=None
      - AUTH_COOKIE_MAX_AGE_SECONDS=604800
generatorOptions:
  disableNameSuffixHash: true
